FROM alpine:3.6

RUN apk --no-cache add \
    nginx

RUN mkdir -p /var/cache/nginx \
  && mkdir /run/nginx

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

WORKDIR /etc/nginx

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
